version: "3"
# https://docs.docker.com/compose/compose-file/

volumes:
  mongo:

services:
  mongo:
    image: docker.sorryasaservice.com/mongodb:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - DB_USER=test
      - DB_PSWD=test
      - DB_NAME=sorry_api
    volumes:
      - mongo:/data/db
    networks:
      - mongo
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  es-master:
    image: sebp/elk:es235_l234_k454
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  es-slave:
    image: sebp/elk:es235_l234_k454
    networks:
      - elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "discovery.zen.ping.unicast.hosts=es-master"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
networks:
  mongo:
  elasticsearch:
