version: "3"

services:
  ante:
    image: docker.aiomatic.com/aiomatic/cloud/ante:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      - cloud
networks:
  cloud: