version: "3"
# https://docs.docker.com/compose/compose-file/

services:
  grails-scaling:
    image: grails-scaling
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      - sorry
networks:
  sorry: