version: "3"
# https://docs.docker.com/compose/compose-file/
volumes:
  my-logs:
services:
  grails-scaling:
    image: grails-scaling
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    volumes:
      #"./host-path-relative-to-compose-file:/container-path"
      - "./../:/app"
      - "my-logs:/var/log/tomcat8"
    ports:
    #host port:container port
      - "8080:8080"
    networks:
      - sorry
    command: ["grails", "run-app"]
  visualizer:
    image: manomarks/visualizer:latest
    ports:
      - "2000:8080"
    volumes:
      - "my-logs:/var/log/tomcat8"
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - sorry
networks:
  sorry: